### ISSUE TITLE
Missing source unit in calculator

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/Semantic_Machine_Learning_Impact_Calculator#4]
I selected `europe-west-2` and I got the following table:
![image](https://user-images.githubusercontent.com/1520666/235358726-a1c19e84-32de-4c2a-8563-f767805627ee.png)
For some reason the source unit is missing. 
I checked, and it's in the data:
![image](https://user-images.githubusercontent.com/1520666/235358789-4f25d75a-3fb2-41df-abc0-4ebbf851bf97.png)

**Comment by dgarijo** [comment]
oh, but I see we have no `symbol` for that unit. I wonder why the other years work ok?

**Comment by dgarijo** [comment]
The unit does not have the right https namespace for wikidata. Issue for me then

**Comment by m-markovic** [comment]
yes ;). I have opened an issue in the relevant repo
