### ISSUE TITLE
Wrong label in second box

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/Semantic_Machine_Learning_Impact_Calculator#7]
A label always says "0" kg of CO2eq. This is wrong:
![image](https://user-images.githubusercontent.com/1520666/235359822-a3575e63-034a-4046-a206-833b0ff28f48.png)

**Comment by dgarijo** [comment]
Also, the references are gone. We should provide the credit to the original paper in a footer

**Comment by stefanogermano** [comment]
> Also, the references are gone. We should provide the credit to the original paper in a footer

Opened a new issue for this (so, it is easier for us to keep track of the activities we still need to complete).

**Comment by m-markovic** [comment]
done
